import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    username: v.string(),
    passwordHash: v.string(),
    role: v.string(),
    kycStatus: v.string(),
    kycStep: v.string(),
    kycIdFront: v.union(v.string(), v.null()),
    kycIdBack: v.union(v.string(), v.null()),
    kycSelfie: v.union(v.string(), v.null()),
    kycDocument: v.union(v.string(), v.null()),
    kycRejectionReason: v.union(v.string(), v.null()),
    kycData: v.optional(v.object({
      name: v.string(),
      phone: v.string(),
      age: v.string(),
      address: v.string(),
      idType: v.string(),
    })),
    phone: v.string(),
    email: v.optional(v.string()),
    fullName: v.optional(v.string()),
    age: v.optional(v.number()),
    ethAddress: v.string(),
    ethPrivateKey: v.string(),
    ethBalance: v.number(),
    ethLocked: v.number(),
    etbBalance: v.number(),
    binanceBalance: v.optional(v.number()),
    bybitBalance: v.optional(v.number()),
    displayName: v.string(),
    bio: v.string(),
    reputation: v.number(),
    totalTrades: v.number(),
    joinedAt: v.string(),
    lastActive: v.string(),
    paymentAccounts: v.optional(v.array(v.object({
      id: v.string(),
      bankName: v.string(),
      accountNumber: v.string(),
      holderName: v.string(),
    }))),
    numericId: v.optional(v.number()),
    isSuspended: v.optional(v.boolean()),
    warnings: v.optional(v.array(v.object({
      id: v.string(),
      message: v.string(),
      createdAt: v.string(),
    }))),
    transactionPin: v.optional(v.string()),
  }).index("by_username", ["username"]).index("by_numericId", ["numericId"]),


  listings: defineTable({
    sellerId: v.string(),
    amountETH: v.number(),
    minLimitETB: v.number(),
    maxLimitETB: v.number(),
    paymentMethods: v.array(v.string()),
    status: v.string(),
    createdAt: v.string(),
    customRateETB: v.optional(v.number()),
    type: v.optional(v.string()),
    paymentAccounts: v.optional(v.array(v.object({
      id: v.string(),
      bankName: v.string(),
      accountNumber: v.string(),
      holderName: v.string(),
    }))),
  }),

  trades: defineTable({
    buyerId: v.string(),
    sellerId: v.string(),
    listingId: v.string(),
    amountETH: v.number(),
    amountETB: v.number(),
    status: v.string(),
    timerExpiresAt: v.string(),
    chat: v.array(v.object({
      senderId: v.string(),
      message: v.string(),
      timestamp: v.string(),
    })),
    proofUrl: v.union(v.string(), v.null()),
    proofStorageId: v.optional(v.union(v.string(), v.null())),
    createdAt: v.string(),
    completedAt: v.optional(v.string()),
    disputeReason: v.optional(v.string()),
    disputedBy: v.optional(v.string()),
    feeETH: v.optional(v.number()),
    selectedPaymentAccount: v.optional(v.object({
      id: v.string(),
      bankName: v.string(),
      accountNumber: v.string(),
      holderName: v.string(),
    })),
  }),

  depositRequests: defineTable({
    userId: v.string(),
    username: v.string(),
    amountUSD: v.number(),
    walletType: v.string(),
    senderReference: v.string(),
    screenshotUrl: v.optional(v.string()),
    status: v.string(),
    adminNote: v.optional(v.string()),
    createdAt: v.string(),
    reviewedAt: v.optional(v.string()),
  }).index("by_status", ["status"]).index("by_userId", ["userId"]),

  notifications: defineTable({
    userId: v.string(),
    type: v.string(),
    message: v.string(),
    isRead: v.boolean(),
    createdAt: v.string(),
  }).index("by_userId", ["userId"]),

  transactions: defineTable({
    userId: v.string(),
    type: v.string(),
    amountETH: v.number(),
    amountUSD: v.number(),
    note: v.string(),
    createdAt: v.string(),
  }).index("by_userId", ["userId"]),

  systemSettings: defineTable({
    etbRatePerDollar: v.number(),
    etbRatePerDollarSell: v.optional(v.number()),
    dailyTradeLimit: v.optional(v.number()),
    flatFeePercent: v.number(),
    maxFeeUSD: v.number(),
    collectedFeesETH: v.number(),
    masterWalletBalanceETH: v.number(),
    masterWalletAddress: v.string(),
    commissionType: v.string(),
    commissionValue: v.number(),
  }),

  supportTickets: defineTable({
    userId: v.string(),
    username: v.string(),
    status: v.string(),
    messages: v.array(v.object({
      senderId: v.string(),
      senderName: v.string(),
      message: v.string(),
      timestamp: v.string(),
    })),
    createdAt: v.string(),
    updatedAt: v.string(),
  }).index("by_status", ["status"]),

  counters: defineTable({
    name: v.string(),
    value: v.number(),
  }).index("by_name", ["name"]),

  withdrawRequests: defineTable({
    userId: v.string(),
    username: v.string(),
    amountUSD: v.number(),
    walletType: v.string(),
    destinationAddress: v.string(),
    status: v.string(),
    adminNote: v.optional(v.string()),
    createdAt: v.string(),
    reviewedAt: v.optional(v.string()),
  }).index("by_status", ["status"]).index("by_userId", ["userId"]),

  adminAuditLogs: defineTable({
    adminId: v.string(),
    adminUsername: v.string(),
    action: v.string(),
    targetId: v.string(),
    targetName: v.string(),
    details: v.string(),
    createdAt: v.string(),
  }).index("by_action", ["action"]),
});

